import React, { useState } from 'react';
import { ChevronDown, ChevronUp, HelpCircle } from 'lucide-react';

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const faqs = [
    {
      question: "Is my capital guaranteed?",
      answer: "No investment in DeFi is 100% risk-free. However, IndexFi minimizes risk by investing only in blue-chip assets and using over-collateralized lending protocols. We prioritize capital preservation over degen yields."
    },
    {
      question: "How is the yield generated?",
      answer: "Yield comes from two sources: 1) Natural market appreciation of the index assets (BTC/ETH/SOL), and 2) Lending interest generated by supplying these assets to audited protocols like Aave and Compound."
    },
    {
      question: "Are the smart contracts audited?",
      answer: "Security is our top priority. We are currently in the internal testing phase. A full audit by a Tier-1 firm (CertiK/Halborn) is scheduled for Q2 2026 before the public mainnet launch."
    },
    {
      question: "Is there a lock-up period?",
      answer: "No. You can withdraw your funds at any time. We believe in complete liquidity and non-custodial ownership."
    }
  ];

  return (
    <section id="faq" className="py-24 bg-slate-900 border-t border-slate-800">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold text-white mb-4">Frequently Asked Questions</h2>
          <p className="text-slate-400">Everything you need to know about the product and security.</p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div key={index} className="border border-slate-800 rounded-2xl bg-slate-950 overflow-hidden">
              <button
                className="w-full flex items-center justify-between p-6 text-left focus:outline-none"
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
              >
                <span className="font-semibold text-white text-lg">{faq.question}</span>
                {openIndex === index ? (
                  <ChevronUp className="h-5 w-5 text-indigo-400" />
                ) : (
                  <ChevronDown className="h-5 w-5 text-slate-500" />
                )}
              </button>

              {openIndex === index && (
                <div className="px-6 pb-6 text-slate-400 leading-relaxed border-t border-slate-800/50 pt-4">
                  {faq.answer}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FAQ;
